# Generated by Django 3.2 on 2026-01-02 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('group', models.CharField(default='customer', max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.branch')),
                ('loginAuth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usedForAgentLogin', to=settings.AUTH_USER_MODEL)),
                ('userAuth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userAdded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fatora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatoraType', models.IntegerField(default=1)),
                ('discount', models.FloatField(default=0)),
                ('totalPrice', models.FloatField()),
                ('balanceDenar', models.FloatField(default=0)),
                ('oldBalanceDenar', models.FloatField(default=0)),
                ('paidAmount', models.FloatField(default=0)),
                ('fatoraDate', models.DateField()),
                ('dateAt', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.agents')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.branch')),
                ('userAuth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('yearId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.commercialyear')),
            ],
        ),
        migrations.CreateModel(
            name='InitAgentsBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denar', models.FloatField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.agents')),
                ('yearId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.commercialyear')),
            ],
        ),
        migrations.CreateModel(
            name='FatoraItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('uploadWeight', models.FloatField(default=0)),
                ('downloadWeight', models.FloatField(default=0)),
                ('cabsa', models.FloatField(default=0)),
                ('dateAt', models.DateTimeField(auto_now=True)),
                ('unitCostPrice', models.FloatField(default=0)),
                ('salePrice', models.FloatField(default=0)),
                ('fatora', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.fatora')),
            ],
        ),
    ]
