# Generated by Django 3.2 on 2026-01-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='group',
        ),
        migrations.AddField(
            model_name='agents',
            name='agentCode',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
