# Generated by Django 3.2 on 2026-01-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0002_auto_20260115_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initagentsbalance',
            old_name='denar',
            new_name='initDenar',
        ),
        migrations.AddField(
            model_name='initagentsbalance',
            name='initDollar',
            field=models.FloatField(default=0),
        ),
    ]
