# Generated by Django 3.2 on 2026-01-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0003_auto_20260116_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='agentCode',
        ),
    ]
