# Generated by Django 3.2 on 2026-01-16 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0004_remove_agents_agentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.branch'),
            preserve_default=False,
        ),
    ]
