# Generated by Django 3.2 on 2026-01-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0005_agents_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='group',
            field=models.CharField(default='agent', max_length=50),
        ),
    ]
