# Generated by Django 3.2 on 2026-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0006_agents_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fatoraitems',
            old_name='cabsa',
            new_name='unitPrice',
        ),
        migrations.RenameField(
            model_name='fatoraitems',
            old_name='downloadWeight',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='fatora',
            name='balanceDenar',
        ),
        migrations.RemoveField(
            model_name='fatora',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='fatora',
            name='fatoraType',
        ),
        migrations.RemoveField(
            model_name='fatora',
            name='oldBalanceDenar',
        ),
        migrations.RemoveField(
            model_name='fatora',
            name='paidAmount',
        ),
        migrations.RemoveField(
            model_name='fatora',
            name='totalPrice',
        ),
        migrations.RemoveField(
            model_name='fatoraitems',
            name='dateAt',
        ),
        migrations.RemoveField(
            model_name='fatoraitems',
            name='salePrice',
        ),
        migrations.RemoveField(
            model_name='fatoraitems',
            name='unitCostPrice',
        ),
        migrations.RemoveField(
            model_name='fatoraitems',
            name='uploadWeight',
        ),
        migrations.AddField(
            model_name='fatoraitems',
            name='InternalDelivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fatoraitems',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fatoraitems',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fatoraitems',
            name='externalURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatoraitems',
            name='itemTitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fatoraitems',
            name='pictureURL',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatoraitems',
            name='shippingType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
