# Generated by Django 3.2 on 2026-01-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0007_auto_20260116_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatora',
            name='branch',
        ),
    ]
