# Generated by Django 3.2 on 2026-01-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0008_remove_fatora_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatora',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='fatora',
            name='fatoraDate',
        ),
    ]
