# Generated by Django 3.2 on 2026-01-18 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Agents', '0010_remove_fatora_userauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatora',
            name='buyingAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fatora',
            name='buyingBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='SentToBuy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fatora',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
