# Generated by Django 3.2 on 2026-01-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0011_auto_20260118_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatora',
            name='status',
        ),
        migrations.AddField(
            model_name='fatoraitems',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
