# Generated by Django 3.2 on 2026-02-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0012_auto_20260131_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='initagentsbalance',
            name='initYuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='initagentsbalance',
            name='initDenar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='initagentsbalance',
            name='initDollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
