# Generated by Django 3.2 on 2026-02-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0013_auto_20260201_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.branch'),
        ),
    ]
