import { RouteInfo } from './sidebar.metadata';
export const SideMenuRouts: RouteInfo[] = [
  // Admin Modules
  {
    path: '/pages/branch/',
    title: 'الفروع ',
    iconType: 'feather',
    icon: 'home',
    class: '',
    index: -1,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['admin'],
    submenu: [],
    selected: false,
  },

  {
    path: '/pages/users/',
    title: 'المستخدمين',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    index: 7,
    badgeClass: '',
    role: ['admin'],
    submenu: [],
    selected: false,
  },

  //*********************************** */

  {
    path: '/acc/box/',
    title: 'الحسابات',
    iconType: 'bootstrap',
    icon: 'bi bi-box-seam sidebarIcon sidebarIconColor',
    class: '',
    index: 0,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['accountant'],
    submenu: [],
    selected: false,
  },

  {
    path: '/acc/agents/',
    title: ' العملاء',
    iconType: 'bootstrap', /// 'feather',
    icon: 'bi bi-people sidebarIcon sidebarIconColor',
    class: '',
    index: 7,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['accountant'],
    submenu: [],
    selected: false,
  },

  {
    path: '/acc/category/',
    title: 'تبويب المصارف',
    iconType: 'bootstrap', /// 'feather',
    icon: 'bi bi-tags sidebarIcon sidebarIconColor',
    class: '',
    index: 11,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['accountant'],
    submenu: [],
    selected: false,
  },

  //  Seller Modules
  {
    path: '/seller/sent/',
    title: 'الطلبات المرسلة',
    iconType: 'bootstrap',
    icon: 'bi bi-send-check sidebarIcon sidebarIconColor',
    class: '',
    index: 0,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['seller'],
    submenu: [],
    selected: false,
  },
  {
    path: '/seller/fwater/',
    title: ' فواتير المبيعات',
    iconType: 'bootstrap',
    icon: 'bi bi-cart4 sidebarIcon sidebarIconColor',
    class: '',
    index: 1,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['seller'],
    submenu: [],
    selected: false,
  },

  {
    path: '/seller/agents/',
    title: ' العملاء',
    iconType: 'bootstrap', /// 'feather',
    icon: 'bi bi-people sidebarIcon sidebarIconColor',
    class: '',
    index: 7,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['seller'],
    submenu: [],
    selected: false,
  },

  //  Agent Modules
  {
    path: '/agent/myorders/',
    title: 'فواتير المبيعات',
    iconType: 'bootstrap',
    icon: 'bi bi-cart4 sidebarIcon sidebarIconColor',
    class: '',
    index: 0,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['agent'],
    submenu: [],
    selected: false,
  },
];
