import { RouteInfo } from './sidebar.metadata';
export const SideMenuRouts: RouteInfo[] = [
  // Admin Modules
  {
    path: '/pages/branch/',
    title: 'الفروع ',
    iconType: 'feather',
    icon: 'home',
    class: '',
    index: -1,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
    selected: false,
  },
  {
    path: '/pages/balances/',
    title: 'ارصدة الفروع ',
    iconType: 'bootstrap',
    icon: 'bi bi-cash-coin sidebarIcon sidebarIconColor',
    class: '',
    index: -1,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
    selected: false,
  },
  {
    path: '/pages/profits/',
    title: 'حساب الارباح ',
    iconType: 'bootstrap',
    icon: 'bi bi-cash-stack sidebarIcon sidebarIconColor',
    class: '',
    index: -3,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
    selected: false,
  },
  {
    path: '/pages/users/',
    title: 'المستخدمين',
    iconType: 'feather',
    icon: 'users',
    class: '',
    groupTitle: false,
    badge: '',
    index: 7,
    badgeClass: '',
    role: ['Admin'],
    submenu: [],
    selected: false,
  },

  //*********************************** */
  {
    path: '/acc/rawItems/',
    title: 'مخزون المواد الخام',
    iconType: 'bootstrap',
    icon: 'bi bi-columns-gap sidebarIcon sidebarIconColor',
    class: '',
    index: 2,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Accountant'],
    submenu: [],
    selected: false,
  },
  {
    path: '/acc/prodItems/',
    title: 'مخزون الإنتاج ',
    iconType: 'bootstrap',
    icon: 'bi bi-slack sidebarIcon sidebarIconColor',
    class: '',
    index: 5,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Accountant'],
    submenu: [],
    selected: false,
  },

  {
    path: '/acc/purchas/',
    title: ' المشتريات',
    iconType: 'bootstrap',
    icon: 'bi bi-basket sidebarIcon sidebarIconColor',
    class: '',
    index: 1,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Accountant'],
    submenu: [],
    selected: false,
  },

  {
    path: '/acc/sale/',
    title: ' المبيعات',
    iconType: 'bootstrap',
    icon: 'bi bi-cart4 sidebarIcon sidebarIconColor',
    class: '',
    index: 8,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Accountant'],
    submenu: [],
    selected: false,
  },

  {
    path: '/acc/box/',
    title: 'ادارة الحسابات',
    iconType: 'bootstrap',
    icon: 'bi bi-box-seam sidebarIcon sidebarIconColor',
    class: '',
    index: 0,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Accountant'],
    submenu: [],
    selected: false,
  },
  {
    path: '/acc/production/',
    title: ' الإنتاج ',
    iconType: 'bootstrap',
    icon: 'bi bi-tools sidebarIcon sidebarIconColor',
    class: '',
    index: 3,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Accountant'],
    submenu: [],
    selected: false,
  },

  {
    path: '/acc/agents/',
    title: ' العملاء',
    iconType: 'bootstrap', /// 'feather',
    icon: 'bi bi-people sidebarIcon sidebarIconColor',
    class: '',
    index: 7,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Accountant'],
    submenu: [],
    selected: false,
  },

  // {
  //   path: '/acc/seller/',
  //   title: ' الموردين ( اصحاب الستوتات ) ',
  //   iconType: 'bootstrap', /// 'feather',
  //   icon: 'bi bi-people-fill sidebarIcon sidebarIconColor',
  //   class: '',
  //   index: 6,
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['Accountant'],
  //   submenu: [],
  //   selected: false,
  // },
  {
    path: '/acc/fixed/',
    title: 'الموجودات الثابتة',
    iconType: 'bootstrap', /// 'feather',
    icon: 'bi bi-stack sidebarIcon sidebarIconColor',
    class: '',
    index: 10,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Accountant'],
    submenu: [],
    selected: false,
  },
  {
    path: '/acc/category/',
    title: 'تبويب المصارف',
    iconType: 'bootstrap', /// 'feather',
    icon: 'bi bi-tags sidebarIcon sidebarIconColor',
    class: '',
    index: 11,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['Accountant'],
    submenu: [],
    selected: false,
  },

  //           StoreKeeper

  {
    path: '/strkepr/rawItems/',
    title: 'مخزون المواد الخام',
    iconType: 'bootstrap',
    icon: 'bi bi-columns-gap sidebarIcon sidebarIconColor',
    class: '',
    index: 2,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['StoreKeeper'],
    submenu: [],
    selected: false,
  },
  {
    path: '/strkepr/prodItems/',
    title: 'مخزون الإنتاج ',
    iconType: 'bootstrap',
    icon: 'bi bi-slack sidebarIcon sidebarIconColor',
    class: '',
    index: 5,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['StoreKeeper'],
    submenu: [],
    selected: false,
  },

  {
    path: '/strkepr/purchas/',
    title: ' المشتريات',
    iconType: 'bootstrap',
    icon: 'bi bi-basket sidebarIcon sidebarIconColor',
    class: '',
    index: 1,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['StoreKeeper'],
    submenu: [],
    selected: false,
  },

  {
    path: '/strkepr/production/',
    title: ' الإنتاج ',
    iconType: 'bootstrap',
    icon: 'bi bi-tools sidebarIcon sidebarIconColor',
    class: '',
    index: 3,
    groupTitle: false,
    badge: '',
    badgeClass: '',
    role: ['StoreKeeper'],
    submenu: [],
    selected: false,
  },

{
  path: '/strkepr/sale/',
  title: ' المبيعات',
  iconType: 'bootstrap',
  icon: 'bi bi-cart4 sidebarIcon sidebarIconColor',
  class: '',
  index: 8,
  groupTitle: false,
  badge: '',
  badgeClass: '',
  role: ['StoreKeeper'],
  submenu: [],
  selected: false,
},
    

  // {
  //   path: '/strkepr/seller/',
  //   title: ' الموردين ( اصحاب الستوتات ) ',
  //   iconType: 'bootstrap', /// 'feather',
  //   icon: 'bi bi-people-fill sidebarIcon sidebarIconColor',
  //   class: '',
  //   index: 6,
  //   groupTitle: false,
  //   badge: '',
  //   badgeClass: '',
  //   role: ['StoreKeeper'],
  //   submenu: [],
  //   selected: false,
  // },
];
