# Generated by Django 3.2 on 2026-01-15 06:15

import Apps.Box.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromAmount', models.FloatField(default=0, help_text='المبلغ ')),
                ('fromBox', models.BooleanField(default=False)),
                ('fromCurrency', models.BooleanField(default=True)),
                ('toAmount', models.FloatField(default=0)),
                ('toBox', models.BooleanField(default=False)),
                ('toCurrency', models.BooleanField(default=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('transactionDate', models.DateField()),
                ('dateAt', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.branch')),
            ],
        ),
        migrations.CreateModel(
            name='InitBranchBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denar', models.FloatField(default=0)),
                ('dollae', models.FloatField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.branch')),
                ('yearId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.commercialyear')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=Apps.Box.models.get_upload_path)),
                ('deleted', models.BooleanField(default=False)),
                ('boxTransaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Box.boxtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('inProfit', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.branch')),
            ],
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Box.category'),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='fromAgent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ffrrooAgent', to='Agents.agents'),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='toAgent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttooAgent', to='Agents.agents'),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='userAuth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='yearId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.commercialyear'),
        ),
    ]
