# Generated by Django 3.2 on 2026-02-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initbranchbox',
            name='yuan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='boxtransaction',
            name='fromAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='boxtransaction',
            name='fromCurrency',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='boxtransaction',
            name='toAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='boxtransaction',
            name='toCurrency',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='initbranchbox',
            name='denar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='initbranchbox',
            name='dollae',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
