# Generated by Django 3.2 on 2026-02-01 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Box', '0002_auto_20260201_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initbranchbox',
            old_name='dollae',
            new_name='dollar',
        ),
    ]
