# Generated by Django 3.2 on 2026-02-02 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agents', '0014_alter_agents_branch'),
        ('Box', '0003_rename_dollae_initbranchbox_dollar'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxtransaction',
            name='buyerOwn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='centralOwn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='fromBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ffrrooBranch', to='Agents.branch'),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='fromCentral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='fromOther',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='toBranch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ttooBranch', to='Agents.branch'),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='toBuyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='toCentral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boxtransaction',
            name='toOther',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='boxtransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.branch'),
        ),
    ]
