# Generated by Django 3.2 on 2026-01-15 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.TextField(blank=True, default='', max_length=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='users')),
                ('privilege', models.CharField(choices=[('admin', 'admin'), ('agent', 'agent'), ('seller', 'seller'), ('accountant', 'accountant'), ('store', 'store')], default='store', max_length=25)),
                ('deleted', models.BooleanField(default=False)),
                ('permission', models.IntegerField(blank=True, default=1, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.agents')),
                ('auth', models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='for_auth_id', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Agents.branch')),
            ],
        ),
    ]
