# Generated by Django 3.2 on 2026-01-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
